site_name: GOST
repo_name: go-gost/gost
repo_url: https://github.com/go-gost/gost
edit_uri: ""

theme:
  name: material
  logo: images/gost.png
  favicon: images/favicon.ico
  custom_dir: overrides
  features:
    - navigation.instant
    # - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - header.autohide
    - navigation.top
    - navigation.footer
    - content.code.copy
  palette: 
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: 白天模式
      primary: teal
      accent: indigo
    - scheme: slate 
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: 夜间模式

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - blog:
      enabled: true
      blog_dir: blog
      post_url_date_format: yyyy
      post_url_format: "{date}/{file}"
      post_date_format: long
      blog_toc: true
      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      archive_url_format: "{date}"
      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      authors: true
      authors_file: "{blog}/.authors.yml"
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-V295TSM2WT

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/go-gost/gost
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/gogost/gost
    - icon: fontawesome/brands/telegram
      link: https://t.me/gogost
  alternate:
    - name: 中文
      link: /
      lang: zh
    - name: English
      link: /en/ 
      lang: en

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2015 - 2025 GOST

nav:
  - 主页: index.md
  - 入门:
    - 快速开始: getting-started/quick-start.md
    - 配置概述: getting-started/configuration-overview.md
    - 常见问题: getting-started/faq.md
  - 概念:
    - 概述: concepts/architecture.md
    - 代理转发和通道: concepts/proxy.md
    - 服务: concepts/service.md
    - 转发链: concepts/chain.md
    - 跳跃点: concepts/hop.md
    - 选择器: concepts/selector.md
    - 认证: concepts/auth.md
    - 分流: concepts/bypass.md
    - 负载均衡: concepts/load-balancing.md
    - 限速限流: concepts/limiter.md
    - 准入控制: concepts/admission.md
    - 域名解析: concepts/resolver.md
    - 主机IP映射: concepts/hosts.md
    - Ingress: concepts/ingress.md
    - 路由器: concepts/router.md
    - 服务发现: concepts/sd.md
    - 数据记录: concepts/recorder.md
    - 服务观测: concepts/observer.md
    - 插件系统: concepts/plugin.md
  - 教程:
    - 协议:
      - 概述: tutorials/protocols/overview.md
      - HTTP: tutorials/protocols/http.md
      - HTTP2: tutorials/protocols/http2.md
      - HTTP3: tutorials/protocols/http3.md
      - SOCKSv4/v5: tutorials/protocols/socks.md
      - Shadowsocks: tutorials/protocols/ss.md
      - SNI: tutorials/protocols/sni.md
      - Relay: tutorials/protocols/relay.md
      - TLS: tutorials/protocols/tls.md
      - DTLS: tutorials/protocols/dtls.md
      - Websocket: tutorials/protocols/ws.md
      - gRPC: tutorials/protocols/grpc.md
      - QUIC: tutorials/protocols/quic.md
      - KCP: tutorials/protocols/kcp.md
      - SSH: tutorials/protocols/ssh.md
      - MTCP: tutorials/protocols/mtcp.md
      - PHT: tutorials/protocols/pht.md
      - Obfs: tutorials/protocols/obfs.md
    - WebAPI:
      - 概述: tutorials/api/overview.md
      - 动态配置: tutorials/api/config.md
    - TLS设置: tutorials/tls.md
    - HTTP通道: tutorials/http-tunnel.md
    - 端口转发: tutorials/port-forwarding.md
    - 反向代理: tutorials/reverse-proxy.md
    - 反向代理隧道: tutorials/reverse-proxy-tunnel.md
    - 反向代理隧道-高可用: tutorials/reverse-proxy-tunnel-ha.md
    - 流量嗅探与MITM: tutorials/sniffing.md
    - HTTP文件服务: tutorials/file.md
    - 探测防御: tutorials/probe-resistance.md
    - PROXY Protocol: tutorials/proxy-protocol.md
    - DNS代理: tutorials/dns.md
    - 透明代理: tutorials/redirect.md
    - 多网络接口: tutorials/multi-homed.md
    - TUN/TAP设备: tutorials/tuntap.md
    - 路由隧道: tutorials/routing-tunnel.md
    - 网络命名空间: tutorials/netns.md
    - ICMP通道: tutorials/icmp.md
    - Unix域套接字重定向: tutorials/unix.md
    - 串口重定向: tutorials/serial.md
    - 监控指标: tutorials/metrics.md
    - 日志: tutorials/log.md
  - 参考:
    - 配置: 
      - 命令行: reference/configuration/cmd.md
      - 配置文件: reference/configuration/file.md
    - 监听器(Listeners):
      - TCP: reference/listeners/tcp.md
      - UDP: reference/listeners/udp.md
      - TLS: reference/listeners/tls.md
      - MTLS: reference/listeners/mtls.md
      - WS: reference/listeners/ws.md
      - MWS: reference/listeners/mws.md
      - HTTP2: reference/listeners/http2.md
      - H2(C): reference/listeners/h2.md
      - gRPC: reference/listeners/grpc.md
      - QUIC: reference/listeners/quic.md
      - PHT: reference/listeners/pht.md
      - HTTP3: reference/listeners/http3.md
      - KCP: reference/listeners/kcp.md
      - SSH: reference/listeners/ssh.md
      - SSHD: reference/listeners/sshd.md
      - RED: reference/listeners/red.md
      - REDU: reference/listeners/redu.md
      - RTCP: reference/listeners/rtcp.md
      - RUDP: reference/listeners/rudp.md
      - DNS: reference/listeners/dns.md
      - TUN: reference/listeners/tun.md
      - TAP: reference/listeners/tap.md
      - ICMP: reference/listeners/icmp.md
      - OHTTP: reference/listeners/ohttp.md
      - OTLS: reference/listeners/otls.md
      - FTCP: reference/listeners/ftcp.md
    - 处理器(Handlers):
      - HTTP: reference/handlers/http.md
      - HTTP2: reference/handlers/http2.md
      - SOCKS4: reference/handlers/socks4.md
      - SOCKS5: reference/handlers/socks5.md
      - Auto: reference/handlers/auto.md
      - Relay: reference/handlers/relay.md
      - TCP: reference/handlers/tcp.md
      - UDP: reference/handlers/udp.md
      - RTCP: reference/handlers/rtcp.md
      - RUDP: reference/handlers/rudp.md
      - SS: reference/handlers/ss.md
      - SSU: reference/handlers/ssu.md
      - SNI: reference/handlers/sni.md
      - SSHD: reference/handlers/sshd.md
      - DNS: reference/handlers/dns.md
      - RED: reference/handlers/red.md
      - REDU: reference/handlers/redu.md
      - TUN: reference/handlers/tun.md
      - TAP: reference/handlers/tap.md
    - 拨号器(Dialers):
      - TCP: reference/dialers/tcp.md
      - UDP: reference/dialers/udp.md
      - TLS: reference/dialers/tls.md
      - MTLS: reference/dialers/mtls.md
      - WS: reference/dialers/ws.md
      - MWS: reference/dialers/mws.md
      - HTTP2: reference/dialers/http2.md
      - H2(C): reference/dialers/h2.md
      - gRPC: reference/dialers/grpc.md
      - QUIC: reference/dialers/quic.md
      - PHT: reference/dialers/pht.md
      - HTTP3: reference/dialers/http3.md
      - KCP: reference/dialers/kcp.md
      - SSH: reference/dialers/ssh.md
      - SSHD: reference/dialers/sshd.md
      - ICMP: reference/dialers/icmp.md
      - OHTTP: reference/dialers/ohttp.md
      - OTLS: reference/dialers/otls.md
      - FTCP: reference/dialers/ftcp.md
    - 连接器(Connectors):
      - HTTP: reference/connectors/http.md
      - HTTP2: reference/connectors/http2.md
      - SOCKS4: reference/connectors/socks4.md
      - SOCKS5: reference/connectors/socks5.md
      - Forward: reference/connectors/forward.md
      - Relay: reference/connectors/relay.md
      - SS: reference/connectors/ss.md
      - SSU: reference/connectors/ssu.md
      - SNI: reference/connectors/sni.md
      - SSHD: reference/connectors/sshd.md
  - 博客: 
    - blog/index.md
  - 捐助: donation.md
  - GOST+: https://gost.plus

